# Changes here will be overwritten by Copier
_commit: 22418f50c2d11c89161b0e967c4ffad9cb6fb18c
_src_path: gh:edgarrmondragon/singer-tap-copier-template
author_email: edgarrm358@gmail.com
author_fullname: "Edgar Ram\xEDrez-Mondrag\xF3n"
author_username: edgarrmondragon
python_main_version: '3.10'
repository_name: tap-shortcut
repository_namespace: edgarrmondragon
repository_provider: github.com
tap_auth_method: API Key
tap_id: tap-shortcut
tap_package_command_line_name: tap-shortcut
tap_package_distribution_name: tap-shortcut
tap_package_import_name: tap_shortcut
tap_source_description: Project management for software teams
tap_source_id: Shortcut
tap_source_name: Shortcut
tap_stream_type: REST
