version: 1
send_anonymous_usage_stats: false
project_id: tap-shortcut
default_environment: dev
plugins:
  extractors:
  - name: tap-shortcut
    namespace: shortcut
    label: Shortcut
    logo_url: https://shortcut.com/icons/icon-512x512.png
    description: Project management for software teams
    repository: https://github.com/edgarrmondragon/tap-shortcut
    docs: https://github.com/edgarrmondragon/tap-shortcut#readme
    pip_url: -e .
    capabilities:
    - catalog
    - discover
    settings_group_validation:
    - [token]
    settings:
    - name: token
      kind: password
      label: Shortcut Token
      description: Shortcut API Token
      documentation: https://developer.shortcut.com/api/rest/v3#Authentication
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-sqlite
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/target-sqlite.git
    config:
      database: output/${MELTANO_EXTRACT__LOAD_SCHEMA}.db
      batch_size: 100
environments:
- name: dev
