name: Test tap-shortcut

on:
  push:
    branches: [main]
    paths:
    - tap_shortcut/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - tap_shortcut/**
    - tests/**
    - pyproject.toml
    - tox.ini
    - uv.lock
    - .github/workflows/test.yml
    - .github/workflows/constraints.txt
  schedule:
  - cron: "0 10 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: "1"
  UV_CONSTRAINT: ${{ github.workspace }}/.github/workflows/constraints.txt

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        python-version:
        - "3.13"
        - "3.12"
        - "3.11"
        - "3.10"
        - "3.9"
        include:
        - { environment: "dependencies", python-version: "3.x" }
        - { environment: "typing",       python-version: "3.x" }

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      id: setup-python
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6.0.1

    - name: Run
      env:
        UV_PYTHON: ${{ steps.setup-python.outputs.python-path }}
        TAP_SHORTCUT_TOKEN: ${{ secrets.TAP_SHORTCUT_TOKEN }}
      run: >
        uvx
        tox -e ${{ matrix.environment || matrix.python-version }}
