name: Update OpenAPI Specification for shortcut.com

on:
  workflow_dispatch:
  schedule:
  # On Fridays
  - cron: '0 12 * * 5'

env:
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.8.11

jobs:
  update_openapi_specification:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
      id: generate-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PRIVATE_KEY }}
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
    - uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
      with:
        version: ${{ env.UV_VERSION }}
    - run: uv run --script scripts/update_openapi.py
    - uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        title: 'chore: Update OpenAPI Specification for shortcut.com'
        token: ${{ steps.generate-token.outputs.token }}
